name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for 'BUILD_CONTAINER_IMAGE' in commit messages
        id: check_commit_message
        run: |
          if git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }} | grep -q 'BUILD_CONTAINER_IMAGE'; then
            echo "::set-output name=build_image::true"
          else
            echo "::set-output name=build_image::false"
          fi

      - name: Build-Push Docker Image
        if: >
          (github.event_name == 'pull_request' && github.event.action == 'closed' &&
          github.event.pull_request.base.ref == 'main') ||
          (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) ||
          steps.check_commit_message.outputs.build_image == 'true'
        run: |
          docker build -t allan1804/guestbook-go:latest .
          docker push allan1804/guestbook-go:latest

